---
# Source: deployment-chart/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simple-service-stable
  labels:
    name: simple-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: simple-service
        version: stable
    spec:
      # imagePullSecrets:
      #   - name: acr-tpark
      containers:
      - name: simple-service
        image: andrebriggs/goserver:v1.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
               name: simple-service-configmap

