---
# Source: deployment-chart/templates/deployment.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: simple-service
  labels:
    name: simple-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: simple-service
        version: canary
    spec:
      imagePullSecrets:
        - name: acr-tpark
      containers:
      - name: simple-service
        image: tpark.azurecr.io/tpark/simple-service:20181118T195312Z
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
          - configMapRef:
               name: simple-service-configmap

